name: weather_core
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0
  equatable: ^2.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
